config/routes.rb
Rails.application.routes.draw do
  scope :answers, as: :answers do
    get :connections, to: 'answers#connections'
    post :log, to: 'answers#log'
  end

  resources :answers, only: [:index]
  get 'answers/:id/show_as_raw', to: 'answers#show_as_raw', as: :answer_as_raw

  resources :exercises, shallow: true do
    resources :questions do
      member do
        resources :answers, only: [:create, :show]

        get 'team/:team_id/answers', to: 'answers#new', as: :new_answer
        post :test_answer
      end

      resources :test_cases
    end
  end

  resources :teams, except: [:show] do
    #resources :users, only: [:show], to: "teams#list_users" do
    #  resources :questions, only: [:show], to: "teams#users_questions"
    #end
    member do
      get :rankings
      get :exercises
      get :users
      get :graph
      get :stats
      post :enroll
      post :unenroll
      get 'list_questions/:exercise_id', to: 'teams#list_questions', as: 'list_exercise_questions'
      get :answers
      get 'users/:user_id', to: 'teams#list_users', as: 'user'
      get 'users/:user_id/questions/:question_id', to: 'teams#user_questions', as: 'user_question'
    end
  end

  resources :answer_connections, only: [:show, :destroy]

  resources :messages, only: [:index, :new, :create, :show]

  resources :recommendations, only: [:index, :show]

  resources :team_exercises, only: [:create, :update, :destroy]

  devise_for :users
  get 'dashboard/home'
  root to: 'dashboard#home'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def home
    @teams_answers = TeacherTeamsLastAnswersQuery
      .new(teacher: current_user)
      .call if current_user.teacher?
    @user_answers = UserLastAnswersQuery.new(current_user).call
    @user_last_messages = current_user.messages_received
      .order(created_at: :desc)
      .limit(5)
    @last_recommendations = TeacherTeamsLastRecommendationsQuery
      .new(current_user)
      .call
    @last_recommendations |= []
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.erb
<%= provide(:header, "Página inicial") %>

<% if current_user.teacher? %>
  <div class="row">
    <div class="col-md-6">

      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Últimas respostas das suas turmas</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <table id="teams-answer-table" class="table table-bordered table-hover">
            <thead>
              <th>Aluno</th>
              <th>Questão</th>
              <th>Tentativa</th>
              <th>Resposta</th>
            </thead>

            <tbody>
              <% @teams_answers.each do |answer| %>
                <tr data-link="<%= answer_path(answer) %>" target="_blank">
                  <td>
                    <%= answer.user.name %>
                  </td>
                  <td>
                    <%= answer.question.title %>
                  </td>
                  <td>
                    <%= answer.attempt %>
                  </td>
                  <td>
                    <%= answer_status_label(answer) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div>
    <div class="col-md-6">

      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Últimas recomendações automáticas para você</h3>
        </div><!-- /.box-header -->
        <div class="box-body">
          <table id="teams-answer-table" class="table table-bordered table-hover">
            <thead>
              <th>Turma</th>
              <th>Questão</th>
              <th>Respostas</th>
              <th>Data de recebimento</th>
            </thead>

            <tbody>
              <% @last_recommendations.each do |recommendation| %>
                <tr data-link="<%= recommendation_path(recommendation) %>" target="_blank">
                  <td>
                    <%= recommendation.team.name %>
                  </td>
                  <td>
                    <%= recommendation.question.title %>
                  </td>
                  <td>
                    <%= recommendation.answers.count %>
                  </td>
                  <td>
                    <%= recommendation.created_at %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div><!-- /.box-body -->
      </div><!-- /.box -->

    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-6">

    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Suas últimas respostas</h3>
      </div><!-- /.box-header -->
      <div class="box-body">
        <table id="user-answers-table" class="table table-bordered table-hover">
          <thead>
            <th>Aluno(a)</th>
            <th>Questão</th>
            <th>Tentativa</th>
            <th>Resposta</th>
          </thead>

          <tbody>
            <% @user_answers.each do |answer| %>
              <tr data-link="<%= new_answer_question_path(answer.question, answer.team, answer_id: answer.id) %>" target="_blank">
                <td>
                  <%= answer.user.name %>
                </td>
                <td>
                  <%= answer.question.title %>
                </td>
                <td>
                  <%= answer.attempt %>
                </td>
                <td>
                  <%= answer_status_label(answer) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.box-body -->
    </div><!-- /.box -->

  </div>
  <div class="col-md-6">

    <div class="box box-info">
      <div class="box-header with-border">
        <h3 class="box-title">Últimas mensagens recebidas</h3>
      </div><!-- /.box-header -->
      <div class="box-body">

        <table id="user-answers-table" class="table table-bordered table-hover dataTable">
          <thead>
            <th>Título</th>
            <th>Enviada por</th>
            <th>Enviada para</th>
            <th>Horário de envio</th>
          </thead>

          <tbody>
            <% @user_last_messages.each do |message| %>
              <tr data-link="<%= message_path(message) %>" target="_blank">
                <td>
                  <%= message.title %>
                </td>
                <td>
                  <%= message.sender.name %>
                </td>
                <td>
                  <%= message.receiver.name %>
                </td>
                <td>
                  <%= message.created_at %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div><!-- /.box-body -->
    </div><!-- /.box -->

  </div>
</div>