config/routes.rb
Rails.application.routes.draw do
  scope :answers, as: :answers do
    get :connections, to: 'answers#connections'
    post :log, to: 'answers#log'
  end

  resources :answers, only: [:index]
  get 'answers/:id/show_as_raw', to: 'answers#show_as_raw', as: :answer_as_raw

  resources :exercises, shallow: true do
    resources :questions do
      member do
        resources :answers, only: [:create, :show]

        get 'team/:team_id/answers', to: 'answers#new', as: :new_answer
        post :test_answer
      end

      resources :test_cases
    end
  end

  resources :teams, except: [:show] do
    #resources :users, only: [:show], to: "teams#list_users" do
    #  resources :questions, only: [:show], to: "teams#users_questions"
    #end
    member do
      get :rankings
      get :exercises
      get :users
      get :graph
      get :stats
      post :enroll
      post :unenroll
      get 'list_questions/:exercise_id', to: 'teams#list_questions', as: 'list_exercise_questions'
      get :answers
      get 'users/:user_id', to: 'teams#list_users', as: 'user'
      get 'users/:user_id/questions/:question_id', to: 'teams#user_questions', as: 'user_question'
    end
  end

  resources :answer_connections, only: [:show, :destroy]

  resources :messages, only: [:index, :new, :create, :show]

  resources :recommendations, only: [:index, :show]

  resources :team_exercises, only: [:create, :update, :destroy]

  devise_for :users
  get 'dashboard/home'
  root to: 'dashboard#home'
end

app/views/shared/_add_controller.js.erb
$('body').data('controller', '<%= controller_name.camelize %>');
$('body').data('action', '<%= action_name %>');

addControllerJS();

app/views/shared/_add_controller_js.js.erb
$('body').data('controller', '<%= controller_name.camelize %>');
$('body').data('action', '<%= action_name %>');

addControllerJS();

app/views/shared/_answer_form.html.erb
<h4>Sua Resposta</h4>
<%= form_for @answer, url: yield(:url), method: :post, remote: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <% unless @team.nil? %>
    <%= f.hidden_field :team_id, value: @team.id %>
  <% end %>

  <div class="form-group">
    <%= f.text_area :content, id: 'editor', class: "form-control" %>
    <div id="editor_div"></div>
  </div>

  <div class="form-group">
    Linguagem permitida: <b style="color: blue"><%= @question.answer_language_allowed.capitalize %></b>
  </div>

  <% if @submitable %>
    <div class="submit">
      <%= f.submit "Submeter resposta", class: "btn btn-primary btn-xs pull-right" %>
    </div>
  <% end %>
<% end %>


<script>
  function adjust_screen() {
//    var new_height =  $('.content-wrapper').height()
//                      - $('#test-results').height()
//                      - $('#error_explanation').height();
//    $('.content-wrapper').height(new_height);
    $('#test-results').empty();
    $('#error_explanation').remove();
    $('#answer-result').remove();
    $('.submit').append('<i class="fa fa-refresh fa-spin"></i>');
  }
//  $('.content-wrapper').height($('.content-wrapper').height() + 300)

  var textarea = $('#editor');
  textarea.hide();

  var editor = ace.edit("editor_div");
  editor.setTheme("ace/theme/twilight");

  <% if @answer.lang_extension == "pas" %>
    editor.getSession().setMode("ace/mode/pascal");
  <% elsif @answer.lang_extension == "c" %>
    editor.getSession().setMode("ace/mode/c_cpp");
  <% elsif @answer.lang_extension == "cpp" %>
    editor.getSession().setMode("ace/mode/c_cpp");
  <% elsif @answer.lang_extension == "python" %>
    editor.getSession().setMode("ace/mode/python");
  <% end %>

  editor.insert("<%= escape_javascript(raw @content) %>");

  // When click put ace editor content in form hidden textarea.
  $('input[name="commit"]').on('click', function() {
    textarea.val(editor.getSession().getValue());
    adjust_screen();
  });
</script>

app/views/shared/_answer_info.html.erb
<table class="table table-bordered">
  <tbody>
    <tr>
      <td><b>Aluno</b></td>
      <td><%= answer.user.name %></td>
    </tr>
    <tr>
      <td><b>Turma</b></td>
      <td><%= answer.team.name %></td>
    </tr>
    <tr>
      <td><b>Questão</b></td>
      <td><%= answer.question.title %></td>
    </tr>
    <tr>
      <td><b>Exercício</b></td>
      <td><%= answer.question.exercise.title %></td>
    </tr>
    <tr>
      <td><b>Tentativa</b></td>
      <td>
        <%= answer.attempt %>
      </td>
    </tr>
    <tr>
      <td><b>Correta</b></td>
      <td>
        <%= answer.correct %>
      </td>
    </tr>
  </tbody>
</table>

<small>
  Realizada em <b><%= answer.created_at.strftime("%d/%m/%Y às %H:%M:%S") %></b>
</small>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      O formulário contém <%= pluralize(object.errors.count, "erro") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% unless object.empty? %>
  <section id="flash-messages" class="content-header">
    <% object.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  </section>
<% end %>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <!-- Default to the left -->
  <strong>Copyright &copy; 2020 - Alexander Kutzke & Diego Cardoso & Rodrigo Walter Ehresmann - v20200603.1 
</footer>

app/views/shared/_header.html.erb
<header class="main-header">
  <a href="<%= root_path %>" class="logo">
    <!-- LOGO -->
    <span class="logo-lg">FARMA-ALG</span>
    <span class="logo-mini">F</span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <% if user_signed_in? %>

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">

            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= gravatar_for(current_user, { class: "user-image" }) %>
              <span class="hidden-xs">
                <%= current_user.name %>
              </span>
            </a>

            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <%= gravatar_for(current_user) %>
                <p>
                  <%= current_user.name %>
                </p>
              </li>

              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<%= edit_user_registration_path %>" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <%= link_to "Sair", destroy_user_session_path,
                                      method: :delete,
                                      class: "btn btn-default btn-flat" %>
                </div>
              </li>

            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Log in", user_session_path %>
          </li>

          <li>
            <%= link_to "Registrar-se", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_paginate.html.erb
<div id="pagination" class="digg_pagination">
  <%= will_paginate object %>
</div>

app/views/shared/_sidebar.html.erb
<div class="main-sidebar">
  <!-- Inner sidebar -->
  <div class="sidebar">
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Menu de operações</li>
        <% if current_user.teacher? %>
          <li>
            <%= link_to exercises_path do %>
              <i class="fa fa-pencil-square-o"></i>
              <span>Meus exercícios</span>
            <% end %>
          </li>

          <li>
            <%= link_to recommendations_path do %>
              <i class="fa fa-magic"></i>
              <span>Recomendações de respostas</span>
            <% end %>
          </li>
        <% end %>

       <li>
         <%= link_to answers_path do %>
           <i class="fa fa-check-square-o"></i>
           <span>Minhas respostas</span>
         <% end %>
       </li>

       <li>
         <%= link_to teams_path do %>
           <i class="fa fa-users"></i>
           <span>Turmas</span>
         <% end %>
       </li>

       <li>
         <%= link_to messages_path do %>
           <i class="fa fa-envelope"></i>
           <span>Mensagens</span>
         <% end %>
       </li>

    </ul><!-- /.sidebar-menu -->

  </div><!-- /.sidebar -->
</div><!-- /.main-sidebar -->

app/views/shared/_test_case_result.html.erb
<% force_show_expected_output |= false %>
<% test_case = test_case_result.test_case %>
<% correct = test_case_result.correct %>
  <div class="row">
    <div class="col-md-12">

      <div class="box box-solid box-<%= correct_style_test_case(test_case_result) %>">
        <div class="box-header">
          <div class="row">
            <div class="col-md-10">
              <i class="<%= correct_icon_test_case(test_case_result) %>"></i>
              <%= test_case_result.test_case.title %>
            </div>

            <div class="col-md-2">
              <div class="btn-group pull-right" role="group">
              <button class="btn btn-primary btn-sm" data-toggle="collapse"
                      data-target="#test-case-input-<%= test_case_result.id %>">
                <i class="fa fa-columns"></i> Entrada 
              </button>
              <button class="btn btn-primary btn-sm" data-toggle="collapse"
                      data-target="#test-case-diff-<%= test_case_result.id %>">
                <i class="fa fa-columns"></i> Saída 
              </button>
              </div>
            </div>
          </div>
        </div><!-- /.box-header -->
        
        <div id="test-case-diff-<%= test_case_result.id %>" class="box-body collapse">
          <% unless test_case_result.test_case.show_expected_output || force_show_expected_output %>
            <p>Saída:</p>
            <table class="diff">
              <tbody>
                <% test_case_result.output.each_line.with_index do |line, index| %>
                  <tr>
                    <th><%= index + 1 %></th>
                    <td class="replace"><%= line %></td>
                  </tr>
                  <% if index == (test_case_result.output.lines.count - 1) && line[-1..-1] == "\n" %>
                    <tr>
                      <th><%= index + 2 %></th>
                      <td class="replace"></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          <% end %>
        </div><!-- /.box-body -->
        
        <div id="test-case-input-<%= test_case_result.id %>" class="box-body collapse">
            <p>Entrada:</p>
            <% if test_case.inputs.first.nil? %>
              Este caso de teste não possuí nenhuma entrada.
            <% else %>
            <table class="diff">
              <tbody>
                <% tam = test_case.inputs.first.lines.count - 1 %>
                <% test_case.inputs.first.each_line.with_index do |line, index| %>
                  <tr>
                    <th><%= index + 1 %></th>
                    <td class="replace"><%= line %></td>
                  </tr>
                  <% if index == tam && line[-1..-1] == "\n" %>
                    <tr>
                      <th><%= index + 2 %></th>
                      <td class="replace"></td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
            <% end %>
        </div><!-- /.box-body -->
      </div><!-- box -->
    </div><!-- row -->
  </div>

<% if test_case_result.test_case.show_expected_output || force_show_expected_output %>
  <script text="text/javascript">
    var baseText = "<%= j raw(test_case_result.test_case.output) %>";
    var newText = "<%= j raw(test_case_result.output) %>";
    var baseTextName = "Esperado";
    var newTextName = "Recebido";
    var tagId = "test-case-diff-<%= test_case_result.id %>"

    diffView(baseText, newText, baseTextName, newTextName, tagId);
  </script>
<% end %>

app/views/shared/test_answer.js.erb
// Page height isn't recalculated when nem elements are appended. This method
// does the job.
function adjustScreen() {
  var new_height = $('.content-wrapper').height() + $('#test-results').height()
                   + $('#error_explanation').height();
  $('.content-wrapper').height(new_height);
}

// Add tests cases results in the page.
function placeTestCasesResults() {
  // Display each result in the screen.
  <% @test_cases_results.each do |test_case_result| %>
      $('#test-results').append("<%= j(render partial: 'shared/test_case_result', locals: {test_case_result: test_case_result}) %>");
  <% end %>
}

// Remove form invalid submition message, if present.
$('#error_explanation').remove();

<% if @answer.content.empty? %>
  $('.fa.fa-refresh.fa-spin').remove();
  $('#new_answer').prepend(
    '<div id="error_explanation"> \
      <div class="alert alert-danger"> \
        Forneça uma resposta! \
      </div> \
    </div>'
  );
<% else %>
  <% if @answer.correct? %>
    $('.fa.fa-refresh.fa-spin').replaceWith('<div id="answer-result"><i class="fa fa-circle text-green"></i> <span>Resposta correta</span></div>');
    placeTestCasesResults();
  <% else %>
    $('.fa.fa-refresh.fa-spin').replaceWith('<div id="answer-result"><i class="fa fa-circle text-red"></i> <span>Resposta incorreta</span></div>');
    placeTestCasesResults();
  <% end %>
<% end %>

//adjustScreen();

app/views/shared/unauthorized.js.erb
$('#flash-messages').remove();
$('.content-wrapper').prepend('<%= escape_javascript(render "shared/flash_messages", object: flash) %>');