config/routes.rb
Rails.application.routes.draw do
  scope :answers, as: :answers do
    get :connections, to: 'answers#connections'
    post :log, to: 'answers#log'
  end

  resources :answers, only: [:index]
  get 'answers/:id/show_as_raw', to: 'answers#show_as_raw', as: :answer_as_raw

  resources :exercises, shallow: true do
    resources :questions do
      member do
        resources :answers, only: [:create, :show]

        get 'team/:team_id/answers', to: 'answers#new', as: :new_answer
        post :test_answer
      end

      resources :test_cases
    end
  end

  resources :teams, except: [:show] do
    #resources :users, only: [:show], to: "teams#list_users" do
    #  resources :questions, only: [:show], to: "teams#users_questions"
    #end
    member do
      get :rankings
      get :exercises
      get :users
      get :graph
      get :stats
      post :enroll
      post :unenroll
      get 'list_questions/:exercise_id', to: 'teams#list_questions', as: 'list_exercise_questions'
      get :answers
      get 'users/:user_id', to: 'teams#list_users', as: 'user'
      get 'users/:user_id/questions/:question_id', to: 'teams#user_questions', as: 'user_question'
    end
  end

  resources :answer_connections, only: [:show, :destroy]

  resources :messages, only: [:index, :new, :create, :show]

  resources :recommendations, only: [:index, :show]

  resources :team_exercises, only: [:create, :update, :destroy]

  devise_for :users
  get 'dashboard/home'
  root to: 'dashboard#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  validates_presence_of :content, :attempt, :lang_extension
  validates_inclusion_of :correct, in: [true, false]

  belongs_to :user
  belongs_to :question
  belongs_to :team

  # The relationship from AnswerConnection is symmetrical, and so we need
  # to check both foreign keys (answer_1 and answer_2) to discover if the
  # connection is made or not.
  has_many :answer_connections_1, class_name: "AnswerConnection", foreign_key: :answer_1_id, dependent: :destroy
  has_many :answer_connections_2, class_name: "AnswerConnection", foreign_key: :answer_2_id, dependent: :destroy

  has_many :test_cases_results, class_name: "AnswerTestCaseResult", dependent: :destroy
  has_many :test_cases, through: :test_cases_results

  scope :by_user, -> (user) do
    return unless user.present?
    where(user: user)
  end

  scope :by_team, -> (team) do
    return unless team.present?
    where(team: team)
  end

  scope :by_question, -> (question) do
    return unless question.present?
    where(question: question)
  end

  # 'correct' is a boolean and so the return status need to check if the value
  # is a boolean.
  scope :correct_status, -> (correct) do
    return unless [true, false].include?(correct)
    where(correct: correct)
  end

  scope :between_dates, -> (start_date, end_date) do
    return unless start_date.present? && end_date.present?
    where("created_at BETWEEN ? AND ?", start_date, end_date)
  end

  scope :created_last, -> do
    order(created_at: :desc)
  end

  scope :by_key_words, -> (key_words) do
    return unless key_words.present?
    search(key_words, fields: [:content])
  end

  # Returns an array of hashes, where the keys are :answer with the answer
  # object, :connection_id and :similarity with the similarity between both answers.
  def similar_answers(threshold:)
    results_1 = answers_similarity_data(answer_connections_1, threshold, :answer_2)
    results_2 = answers_similarity_data(answer_connections_2, threshold, :answer_1)
    (results_1 + results_2)
  end

  # Get similarity between two users, if already calculated.
  def similarity_with(answer)
    query_result = AnswerConnectionQuery.new.get_similarity(self, answer).first
    if query_result then query_result.similarity else nil end
  end

  private

  # Build an array of hashes, where a hash contains the answers object,
  # connection id and the similarity between both answers.
  def answers_similarity_data(connections, threshold, field_name)
    AnswerConnectionQuery.new(connections)
      .connections_by_threshold(min: threshold).map { |connection|
        { answer: connection.send(field_name), connection_id: connection.id,
          similarity: connection.similarity }
      }
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include AnswerObjectToGraph
  include AnswerLanguageExtension
  include ApplicationHelper

  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :find_question, only: [:new, :create]
  before_action :find_answer, only: [:show, :show_as_raw, :log]
  before_action :save_answer_url, only: [:show]

  def index
    date_range = split_date_range

    unless params[:correct].blank?
      correct = params[:correct] == "true" ? true : false
    else
      correct = nil
    end

    @answers = Answer
      .where(user: current_user)
      .by_team(params[:teams])
      .by_question(params[:questions])
      .between_dates(date_range[0], date_range[1])
      .correct_status(correct)
      .order(created_at: :desc)
      .paginate(page: params[:page], per_page: 15)
  end

  def new
    @answer = Answer.new
    @answer.lang_extension = answer_language_extension(@question)
    @team = Team.find(params[:team_id])

    selected_answer = Answer.find_by(id: params[:answer_id])
    @content =  ""
    @results = []
    @test_cases_results = []

    if selected_answer
      Log.create!(
        operation: Log::ANSW_SHOW,
        user: current_user,
        question: selected_answer.question
      )

      @content = selected_answer.content
      @test_cases_results = selected_answer.test_cases_results

      results = AnswerTestCaseResult.where(answer: selected_answer)
      @results = []
      results.each { |result|
        @results << {
          test_case: result.test_case,
          correct: selected_answer.correct,
          output: result.output
        }
      }
    end

    team_exercise = TeamExercise.find_by(team_id: @team.id, exercise_id: @question.exercise_id)

    flash.now[:info] = "Este é um exercício de recomendação, que não altera sua pontuação no ranking." if @question.question_type != "normal"

    if !@team || (team_exercise && team_exercise.active)
      @submitable = true

      flash.now[:info] = "Você já respondeu corretamenta esta questão. Sinta-se a
        vontade para realizar novas tentativas, mas a partir de agora, elas não
        incrementarão seu score nem surtirão qualquer efeito sobre o score desta
        questão." if @question.answered_by_user?(
          current_user,
          team: @team,
          only_correct: true
        )

    else
      @submitable = false

      flash.now[:info] = "O exercício dessa questão não esta mais disponível para ser respondido."
    end
  end

  def create
    @answer = @question.answers.build(answer_params.merge(user: current_user))
    @answer.lang_extension = answer_language_extension(@question)
    creator = AnswerCreator::Creator.new(@answer)
    creator.create unless @answer.content.empty?
    @results = creator.test_cases_results
    @test_cases_results = creator.answer.test_cases_results

    respond_to { |format| format.js { render 'shared/test_answer' } }
  end

  def show
    Log.create!(operation: Log::ANSW_SHOW, user: current_user, question: @answer.question)
    @question = @answer.question

    respond_to do |format|
      format.html {
        @similar_answers = @answer.similar_answers(
          threshold: Figaro.env.similarity_threshold.to_f
        )
      }
      format.js { @node_html_id = params[:node_html_id] }
    end
  end

  def show_as_raw
    Log.create!(operation: Log::ANSW_SHOW, user: current_user, question: @answer.question)
    render layout: false
  end

  def connections
    connections = AnswerConnectionQuery.new.connections_group(
      answers: params[:answers], type: params[:type].to_sym)

    @connections = connections.each.inject([]) do |array, connection|
      hash = {}
      hash.merge!(connection.slice(:id, :similarity).symbolize_keys)

      connection.slice(:answer_1, :answer_2).each do |answer|
        answer_key = answer[0].to_sym
        answer_obj = answer[1]
        hash[answer_key] = answer_object_to_graph(answer_obj)
      end

      array << hash
    end

    respond_to { |format| format.json { render json: @connections } }
  end

  def log
    Log.create!(operation: Log::ANSW_SHOW, user: current_user, question: @answer.question)
  end

  private

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def correct?(results)
    results.each { |result| return false if result[:status] == :error }
    true
  end

  def answer_params
    params.require(:answer).permit(:content, :team_id)
  end

  def find_question
    @question = Question.find(params[:id])
  end

  # Add answer url in sessions to be used in a redirect when an answer
  # connection is deleted.
  def save_answer_url
    session[:previous_answer_url] = answer_url(@answer)
  end

  def split_date_range
    params[:date_range] ? params[:date_range].split("_") : []
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
  def correct_icon_test_case(test_case_result)
    return "fa fa-check" if test_case_result.correct
    "fa fa-close"
  end
  
  def correct_style_test_case(test_case_result)
    return "success" if test_case_result.correct
    "danger"
  end

  def correct_icon(answer)
    return "fa fa-check" if answer.correct?
    "fa fa-close"
  end

  def correct_style(boolean)
    return "success" if boolean == true
    "danger"
  end
end

app/views/answers/_answer_content_modal.html.erb
<div class="modal" id="answer-content-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <button id="close" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Resposta</h3>
      </div>

      <div class="modal-body">
        <%= render "shared/answer_form" %>
      </div>

    </div>
  </div>
</div>

<script>
  $('input[name=commit]').hide();
  // 'editor' var comes from answer_form.
  editor.setOptions( { readOnly: true } );
  editor.setValue("<%= raw(escape_javascript answer.content) %>", 1);
</script>

app/views/answers/_answer_modal.html.erb
<div class="modal" id="answer-modal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button id="close" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <br></br>
        <%= @answer.user.name %>
      </div>

      <div class="modal-body">
        <h3>Detalhes da resposta</h3>

        <%= render partial: 'shared/answer_info', locals: { answer: @answer } %>
        <br></br>

        <table style="width: 100%">
          <tbody>
            <tr>
              <td>
                <button id="show-answer" class="btn btn-primary text-center"
                        style="width: 100%">Visualizar resposta</button>
              </td>
            </tr>
            <tr>
              <td>
                <%= link_to(
                  "Exibir mais detalhes",
                  answer_path(@answer),
                  method: :get,
                  class: "btn btn-primary text-center",
                  style: "width: 100%",
                  target: "_blank"
                ) %>
              </td>
            </tr>
            <tr>
              <td>
                <button id="add-answer-<%= @answer.id %>-similar" class="btn btn-primary text-center"
                        style="width: 100%">Adicionar respostas semelhantes</button>
              </td>
            </tr>
            <tr>
              <td>
                <%= link_to(
                  "Enviar mensagem ao aluno",
                  new_message_path(receiver_ids: [@answer.user.id], answer_ids: [@answer.id]),
                  method: :get,
                  class: "btn btn-primary text-center",
                  style: "width: 100%",
                  target: "_blank"
                ) %>
              </td>
            </tr>
          </tbody>
        </table>

        <hr></hr>

          <h3>Resultados dos casos de teste</h3>

          <% @answer.test_cases_results.each do |test_case_result| %>
            <%= render partial: "shared/test_case_result", locals: { test_case_result: test_case_result } %>
          <% end %>


      </div>
    </div>
  </div>
</div>

<script text="text/javascript">
  $('#answer-container').on('hidden.bs.modal', function () {
    $("#<%= @node_html_id %>").attr('fill', setNodeCollor(<%= @answer.correct %>));
  });

  $('#show-answer').click(function() {
    showModal('answer-content', true, function(modalName) {
      var div = $(document.createElement('div'))
      div.attr('id', modalName + '-container');
      $('body').append(div);
      $(div).html("<%= escape_javascript(render partial: 'answer_content_modal', locals: { answer: @answer }) %>");
      $('body').append(div);
    });

    $.ajax({
      type: "POST",
      url: "<%= answers_log_path %>",
      dataType: "script",
      data: { id: "<%= @answer.id %>" }
    });
  });
</script>

app/views/answers/_answers.html.erb
<table id="answers-table" class="table table-bordered table-hover" role="grid">
  <thead>
    <tr role="row">
      <th class="sorting" style="width: 130px" aria-sort="ascending">Turma</th>
      <th class="sorting" style="width: 170px" aria-sort="ascending">Exercício</th>
      <th class="sorting" style="width: 170px">Questão</th>
      <th class="sorting" style="width: 10px">Tentativa</th>
      <th class="sorting" style="width: 10px">Horário</th>
      <th class="sorting" style="width: 10px">Resposta</th>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr role="row" class="odd" data-link="<%= new_answer_question_path(answer.question, answer.team, answer_id: answer.id) %>" >
        <td>
          <%= answer.team.name %>
        </td>
        <td>
          <%= answer.question.exercise.title %>
        </td>
        <td>
          <%= answer.question.title %>
        </td>
        <td class="text-center">
          <%= answer.attempt %>
        </td>
        <td class="text-center">
          <%= answer.created_at.to_formatted_s(:db)  %>
        </td>
        <td class="text-center">
          <%= answer_status_label(answer) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/answers/_filters.html.erb
<div class="box box-default">
  <div class="box-body">

    <div class="row">
      <div class="col-md-6">
        <label for="daterange-btn">Intervalo de tempo: </label>
        <div class="input-group">
          <%= text_field_tag(
            :date_range,
            nil,
            class: "btn btn-default pull-right",
            id: "daterange-btn"
          ) %>
        </div>
      </div>

      <div>
        <label for="sel1">Classificação da resposta:</label>

        <%= select_tag(
          "correct",
          "<option></option>
          <option value='true'>Correta</option>
          <option value='false'>Incorreta</option>"
          .html_safe,
          class: "form-control"
        ) %>
      </div>
    </div>

    <br></br>

    <div class="row">
      <div class="col-md-6">
        <div class="box box-default">
          <div class="box-header with-border">
            <h3 class="box-title">Disciplinas</h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse">
                <i class="fa fa-minus"></i>
              </button>
            </div><!-- /.box-tools -->
          </div><!-- /.box-header -->
          <div class="box-body">
            <table class="table table-condensed">
              <tbody>
                <% current_user.teams.each do |team| %>
                  <tr>
                    <td>
                      <%= check_box_tag "teams[]", team.id %>
                      <%= team.name %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div><!-- /.box-body -->
        </div><!-- /.box -->
      </div>

      <div class="col-md-6">
        <div class="box box-default collapsed-box">
          <div class="box-header with-border">
            <h3 class="box-title">Questões</h3>
            <div class="box-tools pull-right">
              <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i></button>
            </div><!-- /.box-tools -->
          </div><!-- /.box-header -->
          <div class="box-body">

            <ul class="list-unstyled">
              <% current_user.teams.each do |team| %>
                <% team.exercises.each do |exercise| %>
                    <li>
                      <%= check_box_tag nil, exercise.id, false, id: "exercise-#{exercise.id}" %>
                      <%= exercise.title %>
                      <ul id="exercise-questions-<%= exercise.id %>">
                        <% exercise.questions.each do |question| %>
                        <li>
                          <%= check_box_tag "questions[]", question.id %>
                          <%= question.title %>
                        </li>
                        <% end %>
                      </ul>
                    </li>
                <% end %>
              <% end %>
            </ul>

          </div><!-- /.box-body -->
        </div>
      </div>

    </div>

    <span class="input-group-btn">
      <%= submit_tag(
        "Buscar respostas",
        id: "search-btn",
        class: "form-control btn btn-flat btn-primary pull-right"
      ) %>
    </span>

  </div>
</div>


<script text="text/javascript">
  <% current_user.teams.each do |team| %>
    <% team.exercises.each do |exercise| %>
      $('#exercise-<%= exercise.id %>').click(function () {
          checked = $(this).is(':checked');
          questions = $('#exercise-questions-<%= exercise.id %> li input')
            .prop('checked', checked);
      });
    <% end %>
  <% end %>
</script>

<script text="text/javascript">
  $('#daterange-btn').daterangepicker({
      autoUpdateInput: false,
      ranges: {
            'Hoje': [moment(), moment()],
            'Otem': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Últimos 7 dias': [moment().subtract(6, 'days'), moment()],
            'Últimos 30 dias': [moment().subtract(29, 'days'), moment()],
            'Esse mês': [moment().startOf('month'), moment().endOf('month')],
            'Último mês': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
          }
  });

  $('#daterange-btn').on('apply.daterangepicker', function(ev, picker) {
      $(this).val(picker.startDate.format('YYYY-MM-DD') + '_' + picker.endDate.format('YYYY-MM-DD'));
  });

  $('#daterange-btn').on('cancel.daterangepicker', function(ev, picker) {
      $(this).val('');
  });
</script>

app/views/answers/_test_case_result.html.erb
<% if correct %>
  <div class="alert alert-success text-left">
    <i class="icon fa fa-check"> <%= test_case.title %></i>
    <div class="pull-right" style="display: block">
      <a href='#input' style="padding: 0 10px" data-toggle='collapse' data-target='#input-<%= test_case.id %>'>Input fornecido</a>
      <a href='#output' data-toggle='collapse' data-target='#output-<%= test_case.id %>'>Output recebido</a>
    </div>
  </div>
<% else %>
  <div class="alert alert-danger text-left">
    <i class="icon fa fa-close"> <%= test_case.title %></i>
    <div class="pull-right" style="display: block">
      <a href='#input' style="padding: 0 10px" data-toggle='collapse' data-target='#input-<%= test_case.id %>'>Input fornecido</a>
      <a href='#output' data-toggle='collapse' data-target='#output-<%= test_case.id %>'>Output recebido</a>
    </div>
  </div>
<% end %>

<div id="input-<%= test_case.id %>"
  class="collapse" style= "border-radius: 5px; margin-bottom: 20px; padding: 5px 5px 5px 5px">
  <div style="margin-bottom: 5px;">
    <b>Inputs:</b>
  </div>

  <% if test_case.inputs.count > 0 %>
    <% test_case.inputs.each do |input| %>
      <table class="diff" style="margin-bottom: 10px">
        <tbody>
          <% input.each_line.with_index do |line, index| %>
            <tr>
              <th><%= index + 1 %></th>
              <td class="replace"><%= line %></td>
            </tr>
            <% if index == (output.lines.count - 1) && line[-1..-1] == "\n" %>
              <tr>
                <th><%= index + 2 %></th>
                <td class="replace"></td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  <% else %>
    <div style="background: white; border-radius: 5px; padding: 10px">
      Nenhum input foi fornecido neste caso de teste.
    </div>
  <% end %>
</div>


<div id="output-<%= test_case.id %>"
  class="collapse" style= "border-radius: 5px; margin-bottom: 20px; padding: 5px 5px 5px 5px">
  <div style="margin-bottom: 5px;">
    <b>Output:</b>
  </div>

  <table class="diff">
    <tbody>
      <% output.each_line.with_index do |line, index| %>
        <tr>
          <th><%= index + 1 %></th>
          <td class="replace"><%= line %></td>
        </tr>
        <% if index == (output.lines.count - 1) && line[-1..-1] == "\n" %>
          <tr>
            <th><%= index + 2 %></th>
            <td class="replace"></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/answers/index.html.erb
<%= provide(:header, "Suas tentativas de resposta") %>

<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <%= form_tag answers_path, method: :get, remote: true, class: "form-inline" do %>
      <div class="input-group margin", style="width: 100%">
        <span class="input-group-btn">
          <a class="btn btn-default btn-flat" data-toggle="collapse" data-target="#filters">
            <i class="fa fa-filter"></i> Filtros
          </a>
        </span>
      </div>
      <div id="filters" class="collapse">
        <br></br>
        <%= render "filters" %>
      </div>
    <% end %>

    <div class="box box-body">
      <div id="answers">
        <%= render "answers" %>
      </div>
    </div>

    <div class="text-center">
      <%= render "shared/paginate", object: @answers %>
    </div>
  </div>
</div>

app/views/answers/index.js.erb
$('#answers').empty();
$('#answers').html('<%= j(render "answers/answers") %>');
$('#pagination').html('<%= j(render "shared/paginate", object: @answers) %>')

app/views/answers/new.html.erb
<%= provide(:header, "Responder questão '#{@question.title}'") %>

<% provide(:url, url_for(:action => 'create', :controller => 'answers')) %>

<% breadcrumb :new_answer, @team, @question %>

<div class="container-fluid">
<div class="row">
  <div class="col-md-12">
    <div class="box box-solid">
      <div class="box-header with-border">
        <h3 class="box-title"><b>Enunciado:</b></h3>
      </div>

      <div class="box-body">
        <%= markdown(@question.description) %>
      </div>
    </div>
  </div>
  
  <!--<div class="col-md-6" style="border-right: 1px solid black">-->
    <%= render "shared/answer_form" %>
    <br></br>
    <div id="test-results">
      <% @test_cases_results.each do |test_case_result| %>
        <%= render partial: 'shared/test_case_result', locals: {test_case_result: test_case_result} %>
      <% end %>
    </div>
    <!--</div>-->


</div>

app/views/answers/show.html.erb
<%= provide(:header, "Visualização da resposta") %>

<div class="row">
  <div class="col-md-6">

    <%= render(
      layout: 'shared/structures/box_default',
      locals: { box_title: "Informações principais" }
    ) do %>

      <%= render partial: 'shared/answer_info', locals: { answer: @answer } %>

      <br></br>

      <%= link_to(
        "Enviar mensagem ao aluno",
        new_message_path(receiver_ids: [@answer.user.id], answer_ids: [@answer.id]),
        method: :get,
        class: "btn btn-primary text-center pull-left",
        target: "_blank"
      ) %>

      <button id="show-answer" class="btn btn-primary pull-right">
        Visualizar resposta
      </button>
    <% end %>

  </div><!-- /.col-md-6 -->

  <div class="col-md-6">

    <%= render layout: 'shared/structures/box_default',
               locals: { box_title: "Informações principais" } do %>

       <% @answer.test_cases_results.each do |test_case_result| %>
         <%= render partial: 'shared/test_case_result',
                    locals: { test_case_result: test_case_result, force_show_expected_output: current_user.admin || current_user == @answer.team.owner } %>
       <% end %>

    <% end %>
  </div>

</div>

<div class="row">
  <div class="col-md-6">
    <%= render layout: 'shared/structures/box_default',
               locals: { box_title: "Respostas semelhantes" } do %>

        <% @similar_answers.each do |object| %>
          <div class="callout callout-<%= correct_style(object[:answer].correct) %>">
            <h4>
              <%= object[:answer].user.name %>
              <%= link_to answer_path(object[:answer].id),
                          class: "label label-default pull-right",
                          style: "margin: 5px", target: "_blank",
                          title: "Visualizar resposta" do %>
                <i class="fa fa-eye"></i>
              <% end %>

              <%= link_to answer_connection_path(object[:connection_id]),
                          class: "label label-default pull-right",
                          style: "margin: 5px", title: "Visualizar relação" do %>
                <i class="fa fa-link"></i>
              <% end %>
            </h4>
            Similaridade
            <div class="progress">
              <div class="progress-bar progress-bar-yellow progress-bar-striped"
                  style="width: <%= object[:similarity] %>%">
                    <%= object[:similarity] %>%
              </div>
            </div>
          </div>
        <% end %>

    <% end %>

  </div>

</div>

<script text="text/javascript">
  $('#show-answer').click(function() {
    showModal('answer-content', true, function(modalName) {
      var div = $(document.createElement('div'))
      div.attr('id', modalName + '-container');
      $('body').append(div);
      $(div).html("<%= escape_javascript(render partial: 'answer_content_modal', locals: { answer: @answer }) %>");
      $('body').append(div);
    });
  });
</script>

app/views/answers/show.js.erb
showModal('answer', true, function(modalName) {
  var div = $(document.createElement('div'))
  div.attr('id', modalName + '-container');
  $('body').append(div);
  $(div).html("<%= escape_javascript(render 'answer_modal') %>");
  $('body').append(div);
});

app/views/answers/show_as_raw.html.erb
<pre>
<%= raw @answer.content %>
</pre>