config/routes.rb
Rails.application.routes.draw do
  scope :answers, as: :answers do
    get :connections, to: 'answers#connections'
    post :log, to: 'answers#log'
  end

  resources :answers, only: [:index]
  get 'answers/:id/show_as_raw', to: 'answers#show_as_raw', as: :answer_as_raw

  resources :exercises, shallow: true do
    resources :questions do
      member do
        resources :answers, only: [:create, :show]

        get 'team/:team_id/answers', to: 'answers#new', as: :new_answer
        post :test_answer
      end

      resources :test_cases
    end
  end

  resources :teams, except: [:show] do
    #resources :users, only: [:show], to: "teams#list_users" do
    #  resources :questions, only: [:show], to: "teams#users_questions"
    #end
    member do
      get :rankings
      get :exercises
      get :users
      get :graph
      get :stats
      post :enroll
      post :unenroll
      get 'list_questions/:exercise_id', to: 'teams#list_questions', as: 'list_exercise_questions'
      get :answers
      get 'users/:user_id', to: 'teams#list_users', as: 'user'
      get 'users/:user_id/questions/:question_id', to: 'teams#user_questions', as: 'user_question'
    end
  end

  resources :answer_connections, only: [:show, :destroy]

  resources :messages, only: [:index, :new, :create, :show]

  resources :recommendations, only: [:index, :show]

  resources :team_exercises, only: [:create, :update, :destroy]

  devise_for :users
  get 'dashboard/home'
  root to: 'dashboard#home'
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!
  before_action :find_exercise, only: [:show, :edit, :update, :destroy, :list]

  def index
    @exercises = Exercise.where(user: current_user).order(:created_at)
                         .paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @exercise = Exercise.new
  end

  def create
    @exercise = current_user.exercises.build(exercise_params)
    if @exercise.save
      flash[:success] = "Exercício criado!"
      redirect_to @exercise
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @exercise.update_attributes(exercise_params)
      flash[:success] = "Exercício atualizado!"
      redirect_to @exercise
    else
      render 'edit'
    end
  end

  def destroy
    @exercise.destroy
    flash[:success] = "Exercício deletado!"
    redirect_to exercises_url
  end

    private

    def exercise_params
      params.require(:exercise).permit(:title, :description, :available,:isRecommendation)
    end

    def find_exercise
      @exercise = Exercise.find(params[:id])
    end
end

app/helpers/exercises_helper.rb
module ExercisesHelper
  # 'CodeRayify' class implementation taken from
  # http://allfuzzy.tumblr.com/post/27314404412/markdown-and-code-syntax-highlighting-in-ruby-on
  #class CodeRayify < Redcarpet::Render::HTML
  #  def block_code(code, language)
  #    CodeRay.scan(code, language).div(:line_numbers => :table)
  #  end
  #end

  # Display in markdown ("prettified").
  def markdown(text)
    #coderayified = CodeRayify.new(no_images: true)

    extensions = { hard_wrap: true, filter_html: true, autolink: true,
                   no_intraemphasis: true, fenced_code_blocks: true,
                   tables: true, superscript: true }

    # markdown = Redcarpet::Markdown.new(coderayified, extensions)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end

  # Pluralize question text.
  def pluralize_questions(count)
    return "#{count} questões cadastradas" if count >= 0
    "#{count} questão cadastrada"
  end

  # Returns a span tag with the right label.
  def question_status(question, team)
    if question.answered_by_user?(current_user, team: team, only_correct: true)
      '<span class="badge bg-green">Correta</span>'
    elsif question.answered_by_user?(current_user, team: team)
      '<span class="badge bg-red text-center" style="width=70px">Errada</span>'
    else
      '<span class="badge bg-gray">Sem resposta</span>'
    end
  end

  # Returns a width property filled according user progress
  # (in the current template, progressbar is filled according the
  # width property, so it must be created dynamically).
  def progress(exercise, team)
    "width: #{exercise.user_progress(current_user, team)}%"
  end
end

app/views/exercises/_form.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <div class="box box-primary">

      <div class="box-body">
        <%= form_for @exercise do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label "Título" %>
            <%= f.text_field :title, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label "Descrição" %>
            <%= f.text_area :description, class: "form-control" %>
          </div>

           <div class="form-group">
            <%= f.label "Usar lista com recomendação de exercícios?" %>
            <%= f.check_box :isRecommendation %>
          </div>

          <%= f.submit yield(:button_text), class: "btn btn-primary pull-right" %>
        <% end %>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
console.log($('textarea')[0])
var simplemde = new SimpleMDE( { element: $('textarea')[0],
                                 toolbar: ["preview",
                                           "|",
                                           "bold",
                                           "italic",
                                           "heading-1",
                                           "heading-2",
                                           "heading-3",
                                           "link",
                                           "image",
                                           "table",
                                           "code",
                                           "quote",
                                           "unordered-list",
                                           "ordered-list",
                                           "|",
                                           "guide"]});
</script>

app/views/exercises/edit.html.erb
<%= provide(:header, "Editar exercício #{@exercise.title}") %>

<%= provide(:button_text, "Salvar") %>

<% breadcrumb :edit_exercise, @exercise %>

<%= render "form" %>

app/views/exercises/index.html.erb
<%= provide(:header, "Lista de exercícios criados") %>

<%= link_to "Criar novo exercício", new_exercise_path, class: "btn btn-primary pull-right" %>
<br></br>
<br></br>

<% @exercises.each do |exercise| %>
  <div class="box box-solid box-default">
    <div class="box-header">
      <h3 class="box-title"><%= exercise.title %></h></h3>
    </div><!-- /.box-header -->
    <div class="box-body">
      <%= markdown(truncate(exercise.description, length: 200, separator: ' ')) %>
    </div><!-- /.box-body -->
    <div class="box-footer">
      <b>Possui <a href="<%= exercise_questions_path(exercise) %>"><%= pluralize_questions(exercise.questions.count) %></a></b>
      <div class="pull-right">
        <%= link_to "Ver", exercise %> |
        <%= link_to "Editar", edit_exercise_path(exercise) %> |
        <%= link_to "Excluir", exercise, method: :delete,
                    data: { confirm: "Tem certeza que deseja excluir?" } %>
      </div>
    </div>
  </div>
<% end %>

<%= render "shared/paginate", object: @teams %>

app/views/exercises/new.html.erb
<%= provide(:header, "Novo exercício") %>

<%= provide(:button_text, "Criar") %>

<% breadcrumb :new_exercise %>

<%= render "form" %>

app/views/exercises/show.html.erb
<%= provide(:header, "Exercício '#{@exercise.title}'") %>

<% breadcrumb :exercise, @exercise %>

<%= link_to "Deletar", @exercise, method: :delete,
                       class: "btn btn-primary pull-right",
                       style: "margin-left: 10px",
                       data: { confirm: "Tem certeza que deseja excluir?" } %>

<%= link_to "Editar", edit_exercise_path(@exercise),
                      class: "btn btn-primary pull-right " %>
<br></br>

<div class="box box-solid box-default">
  <div class="box-header">
    <h3 class="box-title"><%= @exercise.title %></h></h3>
  </div><!-- /.box-header -->
  <div class="box-body">
    <%= markdown(@exercise.description) %>
  </div><!-- /.box-body -->
  <div class="box-footer">
    <a href="<%= new_exercise_question_path(@exercise) %>" class="btn btn-primary pull-right">
      <i class="fa fa-plus-square-o" aria-hidden="true"></i>
      Adicionar questão
    </a>

    <b>Possui <a href="<%= exercise_questions_path(@exercise) %>"><%= pluralize_questions(@exercise.questions.count) %></a></b>
  </div>
</div>